'use client'

import Head from "next/head";
import React, { useEffect } from "react";
import Aos from "aos";
import 'aos/dist/aos.css' 
import Header from "../components/HomePage/Header";
import { Hero } from "../components/HomePage/Hero";
import { About } from "../components/HomePage/About";
import { Benefit } from "../components/HomePage/benefit/Benefit";
import { Partner } from "../components/HomePage/partner/Partner";
import { Footer } from "../components/HomePage/footer/Footer";

export default function Home() {
  useEffect(() => {
    Aos.init();
    console.log('aos', Aos)
  }, [])
  return (
    <>
      <Head>
        <title>TicketingLabsNFT - NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black">
        <Header />
        <Hero/>
        <About/>
        <Benefit/>
        <Partner/>
        <Footer/>
      </main>
    </>
  );
}
