import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";
import { Heroes } from "../components/Heroes";
import { HeaderApps } from "../components/apps/HeaderApps";
import Gallery from "../components/mynft/Gallery";

const MyNFT = () => {
  return (
    <>
      <Head>
        <title>NFT Ticketing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderApps/>
        <Gallery/>
      </main>
    </>
  );
};

export default MyNFT;
